---
title: "Team 199: Olympics"
subtitle: "STA 199 Project"
format: html
editor: visual
---

# Project Abstract

Add text

```{r}

library(tidyverse)
library(tidymodels)
library(lubridate)

olympics <- read.csv("data/olympics.csv") 
glimpse(olympics)
```

```{r}

olympics_new <- olympics |> 
  mutate(BMI = (Weight/(Height/100)^2), medalyesno = if_else(is.na(Medal), "no", "yes"))

olympics_new <- as.data.frame(olympics_new)
  
```

```{r}

olympics_new |> 
  filter(Sport == "Swimming",
         medalyesno == "yes",
         Year > 1999) |>
  mutate(medal = as.factor(Medal),
         medal = fct_relevel(Medal, "Gold", 
                             "Silver", "Bronze")) |>
  ggplot(aes(x = Team, fill = medal)) + 
    geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

olympics_new |> 
  filter(Sport == "Swimming",
         Year > 1999,
         Team == c("Australia", "China", "France",
                   "Germany", "Japan", "Netherlands",
                   "United States")) |>
  mutate(medal = as.factor(Medal),
         medal = fct_relevel(Medal, "Gold", 
                             "Silver", "Bronze")) |>
  ggplot(aes(x = Team, fill = medal)) + 
    geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~Sex)
```

```{r}

olympics_new |> 
  filter(Sport == "Swimming", Year > 1999) |>
  mutate(medal = as.factor(Medal), medal = fct_relevel(Medal, "Gold", "Silver", "Bronze")) |>
  ggplot(aes(x = BMI, y = medal)) + 
    geom_boxplot() + 
  facet_wrap(~Sex)

olympics_new |> 
  filter(Sport == "Swimming", Year > 1999) |>
  mutate(medal = as.factor(Medal), medal = fct_relevel(Medal, "Gold", "Silver", "Bronze")) |>
  ggplot(aes(x = Height, y = medal)) + 
    geom_boxplot() + 
  facet_wrap(~Sex)

olympics_new |> 
  filter(Sport == "Swimming", Year > 1999) |>
  mutate(medal = as.factor(Medal), medal = fct_relevel(Medal, "Gold", "Silver", "Bronze")) |>
  ggplot(aes(x = Weight, y = medal)) + 
    geom_boxplot() + 
  facet_wrap(~Sex)

olympics_new |> 
  filter(Sport == "Swimming", Year > 1999) |>
  mutate(medal = as.factor(Medal), medal = fct_relevel(Medal, "Gold", "Silver", "Bronze")) |>
  ggplot(aes(x = Age, y = medal)) + 
    geom_boxplot() + 
  facet_wrap(~Sex) + labs(title = "Male and Female Age vs. Medal Earned",
                          x = "Type of Medal Earned", y = "Age of Athlete")

```

```{r}

athlete_count_by_medal_status <- olympics |>
  summarise(count = n())



```

```{r}

olympians_per_team <- olympics |>
  group_by(Team) |>
  summarise(count = n()) |>
  arrange(desc(count))


N <- 20
top_n_teams <- olympians_per_team[1:N, ]


ggplot(top_n_teams, aes(x = Team, y = count)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Number of Olympians per Team (Top 20)",
       x = "Team",
       y = "Number of Olympians")


```

```{r}
olympians_per_games <- olympics |>
  group_by(Games) |>
  summarise(count = n()) |>
  arrange(Games) 

ggplot(olympians_per_games, aes(x = Games, y = count)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Number of Olympians per Olympic Games",
       x = "Olympic Games",
       y = "Number of Olympians") 


```

```{r}
olympians_per_sport <- olympics |>
  group_by(Sport) |>
  summarise(count = n()) |>
  arrange(desc(count))

ggplot(olympians_per_sport, aes(x = Sport, y = count)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Number of Olympians per Sport",
       x = "Sport",
       y = "Number of Olympians")


```

```{r}
N <- 10

olympians_per_sport <- olympics |>
  group_by(Sport) |>
  summarise(count = n()) |>
  arrange(desc(count)) |>
  slice_head(n = N)

ggplot(olympians_per_sport, aes(x = Sport, y = count)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Number of Olympians for the Most Popular Sports (Top 10)",
       x = "Sport",
       y = "Number of Olympians")


```

```{r}

olympics_new |> 
  filter(Sport == "Swimming", Medal == "Gold", Year > 1999) |>
  ggplot(aes(x = Team)) + 
    geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + labs(title = "Swimming Gold Medals Recieved per Country", x = "Country", y = "Number of Gold Medals")
```
