<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Team 199: Olympics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Team 199: Olympics</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#research-question-data" id="toc-research-question-data" class="nav-link" data-scroll-target="#research-question-data">Research question &amp; Data</a></li>
  <li><a href="#literature" id="toc-literature" class="nav-link" data-scroll-target="#literature">Literature</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Team 199: Olympics</h1>
<p class="subtitle lead">What factors best predict Olymic swimming success?</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Throughout our project, we want to explore the relationship between Olympic athletes’ traits and successful performance in swimming. We aim to determine which traits—between nationality, BMI, weight, age, and height—influence athletes’ performance. We seek to answer the question: which trait or traits ultimately affect Olympic swimmers the most? Within this question, we investigate event, country, sex, medal, height, and weight. We hypothesize that height and nationality will impact Olympic swimmers the most. Filtering the data to address Olympic swim meets from the year 1992 and beyond, we aim to answer our research question via visually comprehensible plots and logistic models.</p>
</section>
<section id="research-question-data" class="level1">
<h1>Research question &amp; Data</h1>
<p>Which traits can best predict Olympic swimmers’ performance (between nationality, height, weight, age, and BMI)?</p>
<p>The data is a cleaned dataset created by a user on Kaggle (https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results), and it originated from http://www.sports-reference.com/, which has a compilation of data from the Olympic games over the years. The dataset has observations for each athlete competing, and it has variables such as team, age, sex, and sport. For each column, the brief definitions are as follows:</p>
<ol type="1">
<li><p><strong>ID</strong> - Unique number for each athlete</p></li>
<li><p><strong>Name</strong> - Athlete’s name</p></li>
<li><p><strong>Sex</strong> - M or F</p></li>
<li><p><strong>Age</strong> - Integer</p></li>
<li><p><strong>Height</strong> - In centimeters</p></li>
<li><p><strong>Weight</strong> - In kilograms</p></li>
<li><p><strong>Team</strong> - Team name</p></li>
<li><p><strong>NOC</strong> - National Olympic Committee 3-letter code</p></li>
<li><p><strong>Games</strong> - Year and season</p></li>
<li><p><strong>Year</strong> - Integer</p></li>
<li><p><strong>Season</strong> - Summer or Winter</p></li>
<li><p><strong>City</strong> - Host city</p></li>
<li><p><strong>Sport</strong> - Sport</p></li>
<li><p><strong>Event</strong> - Event</p></li>
<li><p><strong>Medal</strong> - Gold, Silver, Bronze, or NA</p></li>
</ol>
</section>
<section id="literature" class="level1">
<h1>Literature</h1>
<p>One published credible journal article on the topic that we are interested in researching is an article published by the Institute of Electrical and Electronics Engineers, which entails an algorithim developed by researchers Wojciech Sałabun et. al to determine a swimmer assessment model based on ten factors: weight, height, age, foot length, arms-height-ratio, swimming technique, flexibility, maximum heart rate, fat index, fat-muscle-ratio, and best FINA result (the athlete’s results against the world record in a given swimming competition). To produce this algorithim, 30 professional male swimmers were assessed in all of these categories. (See article here: https://ieeexplore.ieee.org/abstract/document/9673753).</p>
<p>Since our research is seeking the physical traits that have the strongest correlation with successful swimmer performance, this article acts as a foundation for our project inspiration.</p>
<p>Other literature provided the basis of our hypothesis in this field of athletic research. A journal article published by Tim Ackland from the the University of Western Australia’s department of Human Movement and Exercise Science lists traits that many professional and Olympic swimmers have that have aided in their past athletic successes. One of these main traits was found to be upper and lower limb length depending on swim event. These results were derived from a myriad of previous swim studies across continents and assessments from youth swimmers, adult swimmers, and professional swimmers alike.</p>
<p>Since the trait that is most correlated with limb length is height, which is in our data set, we hypothesize that height will be greatly correlated with the success of an Olympic swimmer. The article claims that height tends to give swimmers a distinct advantage in the pool, as made apparent by elite international male and female swimmers such as Nathan Adrian (6’6), Kilment Kolesnikov(6’5), Michael Andrew (6’5), Sarah Sjostrom (6’0), Olympic gold medalist Simone Manuel (5’11), and Olympic gold medalist Katie Ledeckey (5’11). In addition, data from the 2016 Olympic finals states that the average height of the finalists in Rio was 6’2 for men and 5’9 for women, which is 5 inches above the global average male and female heights respectively (worlddata.info and ourworldindata.org). Other traits that seem to lead to athletic success in the sector of swimming that were listed in Ackland’s article include tall stature, limb length, chest girth, foot length, arm span, body mass, and psychology (https://ro.ecu.edu.au/cgi/viewcontent.cgi?article=8132&amp;context=ecuworks#page=76).</p>
<p>Our research question, “Which trait ultimately affects Olympic swimmers’ performance the most?” builds upon this article because it would lend more concrete statistical evidence to many observed correlations such as height. Although this article provides evidence to its claims by citing corresponding examples of athletes and previous research, our research question will be able to build upon these claims by calling more physical traits into question, and specific swimming events in which these traits have the strongest correlations with success.</p>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<p>The differences between swimmers are best shown through data visualization. The data was filtered to show only results from the 1992 Summer games and the years since, to make it more applicable to modern games while maintaining a large sample size. The relationship between national origin and medal results was shown through a stacked bar plot that shows the number of each type of medals earned by each country with at least ten medals.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/country_comparisons-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>These visualizations show a very strong relationship between national origin and Olympic swimming performance. Australian and American swimmers had by far the majority of all medal types, while the majority of countries had a negligible number. National origin is thus a strong predictive factor for swimming performance.</p>
<p>Next, parallel boxplots were used to compare the ranges for athlete’s physical traits and age, comparing different medalists to non-medalists. Each plot was faceted by age to determine if trends in age or physical characteristics differed for males and females.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/athlete_stats-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/athlete_stats-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/athlete_stats-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/athlete_stats-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The typical BMI, height, and weight for swimmers increased slightly as their medal rank did (so the typical gold winner was slightly taller and heavier, and had a higher BMI than the other medalists as well as non-medalists). These results are conserved across sex in each category. The age of the swimmer had no meaningful correlation with results; there are slight differences between medal categories but no large effect or clear trend.</p>
<p>A logistic regression model was chosen to determine which variables have the strongest effect on swimmer performance. For this model, all medals were merged into one category, and the model attempted to predict whether or not an athlete would win any medal based on their traits. Based on the visualization results, Age was excluded as a variable to be tested, leaving Team, Height, Weight, and BMI. The model only included the countries that had earned ten or more medals, making the assumption that athletes from other countries had a negligible likelihood of winning.</p>
<p>The first attempt at the model used only <strong>Team</strong> as a predictor, and yielded an AIC of 321.2.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1          395.     377  -147.  321.  376.     293.         364   378</code></pre>
</div>
</div>
<p>Next, BMI was added to the model (yielding <strong>Team + BMI</strong>). This raised the AIC to 322.5, so BMI was discarded as a predictor.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1          395.     376  -146.  322.  381.     292.         362   377</code></pre>
</div>
</div>
<p>With BMI discarded, Weight was tested next (yielding <strong>Team + Weight</strong>). This lowered the AIC to 319.5, so it will be carried forward.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1          395.     376  -145.  320.  378.     290.         362   377</code></pre>
</div>
</div>
<p>Next, Height was added to the model (yielding <strong>Team + Weight + Height</strong>), for an even lower AIC of 317.8.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1          395.     376  -143.  318.  381.     286.         361   377</code></pre>
</div>
</div>
<p>Next, new combinations of these three variables were tested. First, Team was removed (yielding <strong>Height + Weight</strong>). This raised the AIC sharply to 392.6, so Team will remain in the model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1          395.     376  -193.  393.  404.     387.         374   377</code></pre>
</div>
</div>
<p>Next, Weight was removed (yielding <strong>Team + Height</strong>). This gave the lowest AIC yet, 317.2, so this is the best model in terms of AIC.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1          395.     377  -144.  317.  376.     287.         363   378</code></pre>
</div>
</div>
<p>Lastly, a model that uses only <strong>Height</strong> allows direct comparison between the Team and Height variables. It yields an AIC of 391.2, far higher than the Team model’s 321.1. Team is therefore the more predictive of the two best variables.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1          395.     377  -194.  391.  399.     387.         376   378</code></pre>
</div>
</div>
<p>This series of logistic models yielded two models with comparable AIC values: Team + Height + Weight and Team + Height. Models that did not incorporate the Team variable had far higher AIC than those that did, while the model with Team alone had an AIC close to the final model. This makes it clear that Team is the variable that best predicts medaling. The p-values of the two best models were checked to determine which yielded more significant results.</p>
<p>The model with <strong>Team + Weight + Height</strong> had a p value of 0.323 for the Weight coefficient, which shows a low level of certainty in this variable.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-11.6760426</td>
<td style="text-align: right;">5.1897384</td>
<td style="text-align: right;">-2.2498326</td>
<td style="text-align: right;">0.0244596</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamCanada</td>
<td style="text-align: right;">-2.4319881</td>
<td style="text-align: right;">0.8117090</td>
<td style="text-align: right;">-2.9961329</td>
<td style="text-align: right;">0.0027343</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamChina</td>
<td style="text-align: right;">-1.8652685</td>
<td style="text-align: right;">0.7009288</td>
<td style="text-align: right;">-2.6611384</td>
<td style="text-align: right;">0.0077877</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamFrance</td>
<td style="text-align: right;">-1.8211837</td>
<td style="text-align: right;">0.7094199</td>
<td style="text-align: right;">-2.5671451</td>
<td style="text-align: right;">0.0102540</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamGermany</td>
<td style="text-align: right;">-1.5421944</td>
<td style="text-align: right;">0.5816299</td>
<td style="text-align: right;">-2.6515048</td>
<td style="text-align: right;">0.0080134</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamGreat Britain</td>
<td style="text-align: right;">-3.1300410</td>
<td style="text-align: right;">1.0777603</td>
<td style="text-align: right;">-2.9042088</td>
<td style="text-align: right;">0.0036818</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamHungary</td>
<td style="text-align: right;">-2.1062137</td>
<td style="text-align: right;">0.8203470</td>
<td style="text-align: right;">-2.5674666</td>
<td style="text-align: right;">0.0102445</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamItaly</td>
<td style="text-align: right;">-1.6384474</td>
<td style="text-align: right;">0.7135594</td>
<td style="text-align: right;">-2.2961613</td>
<td style="text-align: right;">0.0216667</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamJapan</td>
<td style="text-align: right;">-2.4885067</td>
<td style="text-align: right;">1.0828470</td>
<td style="text-align: right;">-2.2981147</td>
<td style="text-align: right;">0.0215553</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamNetherlands</td>
<td style="text-align: right;">-1.6327879</td>
<td style="text-align: right;">0.7278732</td>
<td style="text-align: right;">-2.2432313</td>
<td style="text-align: right;">0.0248819</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamRussia</td>
<td style="text-align: right;">-2.0623226</td>
<td style="text-align: right;">0.6547879</td>
<td style="text-align: right;">-3.1496040</td>
<td style="text-align: right;">0.0016349</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamSouth Africa</td>
<td style="text-align: right;">-1.8022148</td>
<td style="text-align: right;">0.8399601</td>
<td style="text-align: right;">-2.1455959</td>
<td style="text-align: right;">0.0319052</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamSweden</td>
<td style="text-align: right;">-1.1190584</td>
<td style="text-align: right;">0.7423960</td>
<td style="text-align: right;">-1.5073605</td>
<td style="text-align: right;">0.1317183</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamUnited States</td>
<td style="text-align: right;">1.6565604</td>
<td style="text-align: right;">0.5241582</td>
<td style="text-align: right;">3.1604204</td>
<td style="text-align: right;">0.0015754</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Weight</td>
<td style="text-align: right;">-0.0302190</td>
<td style="text-align: right;">0.0306008</td>
<td style="text-align: right;">-0.9875227</td>
<td style="text-align: right;">0.3233865</td>
</tr>
<tr class="even">
<td style="text-align: left;">Height</td>
<td style="text-align: right;">0.0751934</td>
<td style="text-align: right;">0.0393608</td>
<td style="text-align: right;">1.9103610</td>
<td style="text-align: right;">0.0560868</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The model with just <strong>Height + Weight</strong> had p values below 0.05 for all coefficients besides Team Sweden (p = 0.109), which is far better than the previous model. Though the AIC values were similar, the difference between p values make the Height + Weight model far superior.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-7.5364541</td>
<td style="text-align: right;">3.0222801</td>
<td style="text-align: right;">-2.493632</td>
<td style="text-align: right;">0.0126444</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamCanada</td>
<td style="text-align: right;">-2.4016185</td>
<td style="text-align: right;">0.8092747</td>
<td style="text-align: right;">-2.967619</td>
<td style="text-align: right;">0.0030012</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamChina</td>
<td style="text-align: right;">-1.8478142</td>
<td style="text-align: right;">0.6986759</td>
<td style="text-align: right;">-2.644737</td>
<td style="text-align: right;">0.0081754</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamFrance</td>
<td style="text-align: right;">-1.7962859</td>
<td style="text-align: right;">0.7071702</td>
<td style="text-align: right;">-2.540104</td>
<td style="text-align: right;">0.0110819</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamGermany</td>
<td style="text-align: right;">-1.4709515</td>
<td style="text-align: right;">0.5768240</td>
<td style="text-align: right;">-2.550087</td>
<td style="text-align: right;">0.0107696</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamGreat Britain</td>
<td style="text-align: right;">-3.1181233</td>
<td style="text-align: right;">1.0775970</td>
<td style="text-align: right;">-2.893589</td>
<td style="text-align: right;">0.0038087</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamHungary</td>
<td style="text-align: right;">-2.0786095</td>
<td style="text-align: right;">0.8191494</td>
<td style="text-align: right;">-2.537522</td>
<td style="text-align: right;">0.0111640</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamItaly</td>
<td style="text-align: right;">-1.6192694</td>
<td style="text-align: right;">0.7117530</td>
<td style="text-align: right;">-2.275044</td>
<td style="text-align: right;">0.0229033</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamJapan</td>
<td style="text-align: right;">-2.5335523</td>
<td style="text-align: right;">1.0810428</td>
<td style="text-align: right;">-2.343619</td>
<td style="text-align: right;">0.0190977</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamNetherlands</td>
<td style="text-align: right;">-1.5083302</td>
<td style="text-align: right;">0.7144247</td>
<td style="text-align: right;">-2.111251</td>
<td style="text-align: right;">0.0347507</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamRussia</td>
<td style="text-align: right;">-1.9544265</td>
<td style="text-align: right;">0.6437147</td>
<td style="text-align: right;">-3.036169</td>
<td style="text-align: right;">0.0023961</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamSouth Africa</td>
<td style="text-align: right;">-1.8619358</td>
<td style="text-align: right;">0.8377047</td>
<td style="text-align: right;">-2.222664</td>
<td style="text-align: right;">0.0262385</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TeamSweden</td>
<td style="text-align: right;">-1.1646447</td>
<td style="text-align: right;">0.7276161</td>
<td style="text-align: right;">-1.600631</td>
<td style="text-align: right;">0.1094587</td>
</tr>
<tr class="even">
<td style="text-align: left;">TeamUnited States</td>
<td style="text-align: right;">1.6256412</td>
<td style="text-align: right;">0.5219540</td>
<td style="text-align: right;">3.114529</td>
<td style="text-align: right;">0.0018424</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Height</td>
<td style="text-align: right;">0.0401009</td>
<td style="text-align: right;">0.0166577</td>
<td style="text-align: right;">2.407350</td>
<td style="text-align: right;">0.0160688</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The final regression equation with the best model is as follows:</p>
<p><span class="math display">\[\log\Big(\frac{p}{1-p}\Big) = -7.5364541 + 0.0401009 \times Height + [TeamCoef.]
\]</span></p>
<p>or:</p>
<p><span class="math display">\[p = \frac{\exp(-7.5364541 + 0.0401009\times Height\ + [TeamCoef.])}{1 + \exp(-7.5364541 + 0.0401009\times Height\ + [TeamCoef.])}\]</span></p>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>All of the tested characteristics except for age showed some small effect on medal results, with a clear trend between placement and each characteristic in the stacked bar plot and the boxplots. High-placing swimmers tended to be slightly taller, heavier, and of a higher BMI than low-placing swimmers. The effect of the physical characteristics, however, was far overshadowed by the effect of national origin. The typical ranges for gold-medal swimmers had significant overlap with those of non-medalists in most comparisons, while dominant countries such as the United States and Australia claimed the vast majority of medals and had a far greater fraction of winners as well.</p>
<p>The logistic model determined how significant the variables actually were in predicting Olympic swimming success. Nationality was found to be by far the most important variable, as it strongly lowered the AIC of the models. Height was also a good predictive variable, as it lowered the AIC even further. BMI was ruled out completely for raising AIC. Weight was considered, as it only slightly raised AIC, but the p value of the weight coefficient was far too high for it to be a reliable predictor.</p>
<p>These results support the idea that national support and the training regimen for Olympic swimmers is far more important than the specifics of their physical traits. Because the medal data favored certain countries, it could be proposed that the main factors that support an Olympian’s success are country-specific factors such as the popularity of their sport or the availability of funding for them to train. While physical characteristics are still important (the data showed that only people with a narrow range of body measurements were even in the competition), national support and other factors are critical for high-level success.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>